blog/urls.py
from . import views
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, CommentCreateView, CommentUpdateView, CommentDeleteView, LikeView, DevelopmentView, notification, SearchView

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/comment/new/',
         CommentCreateView.as_view(), name='comment-create'),
    path('post/<int:post_pk>/comment/<int:pk>/update/',
         CommentUpdateView.as_view(), name='comment-update'),
    path('post/<int:post_pk>/comment/<int:pk>/delete/',
         CommentDeleteView.as_view(), name='comment-delete'),
    path('about/', views.about, name='blog-about'),
    path('like/<int:pk>/', LikeView, name='like_post'),
    path('team/', DevelopmentView, name="team"),
    path('notification/<int:pk>', notification, name="notification"),
    path('searchuser/', SearchView.as_view(), name='search'),
]

minor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site
from users import views as user_views
from event import views as event_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('login/', user_views.CustomLogin.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('facelogin/', user_views.TwoFactorAuth, name='twofactorauth'),
    path('facelogin/authenticate/', user_views.postFaceLogin, name='postfacelogin'),
    path('profile/', user_views.profile, name="profile"),
    path('profile/<int:pk>',
         user_views.ProfileDetailView.as_view(template_name='users/profile_page.html'), name="profile-page"),
    path('profile/webcam', user_views.webcam, name='webcam'),
    path('profile/headshot', user_views.postHeadShot, name='postheadshot'),
    path('', include('blog.urls')),
    path('Query/', include('quesans.urls')),
    path('follow/<int:pk>', user_views.follow, name='follow'),
    # path('follow_request/<int:pk>',
    #      user_views.follow_request, name='follow-request'),
    path('accept_request/<int:pk>',
         user_views.accept_follow_request, name='accept-follow-request'),
    path('find_friends/',
         user_views.findFriend, name='find-friend'),
    path('suggestions/', user_views.ProfileListView.as_view(
        template_name='users/suggestions.html'), name='suggestions'),
    path('tinymce/', include('tinymce.urls')),
    path('create_event/', event_views.EventCreateView.as_view(
        template_name='event/create.html'), name='create-event')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quesans/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='quesans'

urlpatterns = [
    path('your-list/<str:filter>',views.YourQuestionListView.as_view(),name='qlist'),
    path('',views.QuestionListView.as_view(),name='clist'),
    path('postanswer/<int:pk>/new/',views.AnswerPostView.as_view(),name='postans'),
    path('post/new/',views.PostQuestionView.as_view(),name='postq'),
    path('searchquestion/',views.SearchView.as_view(),name='qsearch'),
    path('voteup/',views.QuesVoteup,name='ques-voteup'),
    path('votedown/',views.QuesVotedown,name='ques-votedown'),
    path('<slug:slug>/',views.QuestionAnswerView.as_view(),name='qthread'),
    path('answer/<int:pk>/',views.AnswerDetail,name='ans-detail'),
    path('answer/reply/', views.reply_page, name="reply"),
    path('Answered/<slug:slug>/',views.QuestionAnswered,name='ques-flag'),
    path('Bookmark/<slug:slug>/',views.BookmarkView,name='ques-bookmark'),
    path('upvote/<slug:slug>/',views.UpvoteView,name='upvote-ans'),
    path('downvote/<slug:slug>/',views.DownvoteView,name='downvote-ans'),
    path('post/<int:pk>/update/',views.QuestionUpdateView.as_view(),name='qupdate'),
    path('post/<int:pk>/delete/',views.QuestionDeleteView.as_view(),name='delquestion'),
    path('postanswer/<int:pk>/delete/',views.AnswerDeleteView.as_view(),name='delanswer'),
    path('postanswer/<int:pk>/update/',views.AnswerUpdateView.as_view(),name='ansupdate'),
]

quesans/forms.py
from django import forms
from . import models
from tinymce import TinyMCE

class PostQues(forms.ModelForm):
    desc = forms.CharField(widget=TinyMCE(mce_attrs={'width': 500}))
    class Meta:
        model = models.Question
        fields =['title','desc','image']

class PostAns(forms.ModelForm):
    answer_text = forms.CharField(widget=TinyMCE(mce_attrs={'width':800}))
    class Meta:
        model = models.Answer
        fields = ['answer_text','is_anonymous']

class PostReply(forms.ModelForm):
    class Meta:
        model = models.Reply
        fields = ['body']
    def __init__(self, *args, **kwargs):
        super(PostReply, self).__init__(*args, **kwargs)
        self.fields['body'].widget.attrs = {'placeholder': 'Reply here...', 'class':'form-control', 'rows':'5'}

quesans/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Question, Answer, Reply
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from . import forms
from .models import Question, Answer
from django.urls import reverse


class QuestionListView(ListView):
    model = Question
    template_name = 'quesans/listall.html'
    context_object_name = 'questions'
    ordering = ['answered','-created_on']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            uplst = []
            downlst = []
            booklst = []
            for question in Question.objects.all():
                if question.qupvote.filter(id=self.request.user.id).exists():
                    uplst.append(question)
                if question.qdownvote.filter(id=self.request.user.id).exists():
                    downlst.append(question)
                if question.bookmarked.filter(id=self.request.user.id).exists():
                    booklst.append(question)
            context['uplst'] = uplst
            context['downlst'] = downlst
            context['booklst']= booklst
            return context
        except:
            return None


class YourQuestionListView(LoginRequiredMixin, ListView):
    model = Question
    template_name = 'quesans/qlist.html'
    context_object_name = 'questions'
    ordering = ['answered','-created_on']

    def get_queryset(self):
        if self.kwargs["filter"] == 'all':
            questions = Question.objects.all().filter(author=self.request.user)
        elif self.kwargs["filter"] == 'answered':
            questions = Question.objects.all().filter(answered=True)
        elif self.kwargs["filter"] == 'pending':
            questions = Question.objects.all().filter(answered=False)
        elif self.kwargs["filter"] == 'bookmarked':
            questions=Question.objects.all().filter(bookmarked__in=[self.request.user])
        return questions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            uplst = []
            downlst = []
            booklst = []
            answlst = []
            pendlst = []
            questions = self.get_queryset()
            for question in questions:
                if question.qupvote.filter(id=self.request.user.id).exists():
                    uplst.append(question)
                if question.qdownvote.filter(id=self.request.user.id).exists():
                    downlst.append(question)
                if question.bookmarked.filter(id=self.request.user.id).exists():
                    booklst.append(question)
            context['uplst'] = uplst
            context['downlst'] = downlst
            context['downlst'] = downlst
            context['bklst'] = booklst
            return context
        except:
            return None


class SearchView(ListView):
    model = Question
    template_name = 'quesans/search-ques.html'
    context_object_name = 'search_results'

    def get_queryset(self):
        result = super(SearchView, self).get_queryset()
        query = self.request.GET.get('search')
        if query:
            postresult = Question.objects.filter(title__contains=query).order_by('-answered','-created_on')
            result = postresult
        else:
            result = None
        return result


class PostQuestionView(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['title', 'desc','image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, "Question posted successfully!")
        return super().form_valid(form)


class QuestionUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Question
    fields = ['title','desc','image','answered']

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, "Question updated successfully!")
        return super().form_valid(form)

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.author:
            return True
        else:
            messages.error(self.request, "Error editing question!")
            return False

    def get_login_url(self):
        if self.request.user.is_authenticated:
            return '/quesans/list/'
        return super().get_login_url()

    def get_absolute_url(self):
        return reverse('quesans:qthread', args=[str(self.question.slug)])

class QuestionDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Question
    success_url = '/Query'

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.author:
            return True
        else:
            messages.error(self.request, "Cannot delete question!")
            return False

class QuestionAnswerView(DetailView):
    model = Question
    context_object_name = 'question'
    slug_url_kwarg = 'slug'

    def get_object(self, queryset=None):
        return Question.objects.get(slug=self.kwargs.get("slug"))

    # get all answers corresponding to the question object
    def get_context_data(self, **kwargs):
        question = self.get_object()
        context = super().get_context_data(**kwargs)
        try:
            ulst = []
            dlst = []
            context['answers'] = Answer.objects.all().filter(question=question)
            for answer in context['answers']:
                if answer.upvote.filter(id=self.request.user.id).exists():
                    lst.append(answer)
                if answer.downvote.filter(id=self.request.user.id).exists():
                    dlst.append(answer)
            context['qupvotelst'] = question.qupvote.all()
            context['qdvotelst'] = question.qdownvote.all()
            context['bklst'] = question.bookmarked.all()
            context['ulst'] = ulst
            context['dlst'] = dlst
            return context
        except:
            print("Error in get_context_data method")
            return None


def AnswerDetail(request, pk):
    answer = get_object_or_404(Answer, id=pk)
    # List of active comments for this post
    replies = answer.replies.filter(active=True)
    upvotes = answer.upvote.all()
    downvotes = answer.downvote.all()
    new_reply = None
    if request.method == 'POST':
        # A comment was posted
        reply_form = forms.PostReply(data=request.POST)
        if reply_form.is_valid():
            # Create Comment object but don't save to database yet
            new_reply = reply_form.save(commit=False)
            # Assign the current answer and user to the comment
            new_reply.answer = answer
            new_reply.user = request.user
            # Save the comment to the database
            new_reply.save()
            # redirect to same page and focus on that comment
            return HttpResponseRedirect(reverse('quesans:ans-detail', args=[str(pk)])+'#'+str(new_reply.id))
    else:
        reply_form = forms.PostReply()
    return render(request, 'quesans/answer_detail.html', {'answer': answer, 'replies': replies, 'reply_form': reply_form,'upvotes':upvotes,'downvotes':downvotes})

class AnswerUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Answer
    fields = ['answer_text','image','is_anonymous']

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, "Answer updated successfully!")
        return super().form_valid(form)

    def test_func(self):
        answer = self.get_object()
        if self.request.user == answer.user:
            return True
        else:
            messages.error(self.request, "Error editing answer!")
            return False

    def get_login_url(self):
        if self.request.user.is_authenticated:
            return '/quesans/list/'
        return super().get_login_url()

    def get_absolute_url(self):
        return reverse('quesans:ans-detail', args=[str(self.answer.pk)])

def reply_page(request):
    if request.method == "POST":
        form = forms.PostReply(request.POST)
        if form.is_valid():
            answer_id = request.POST.get('answer_id')  # from hidden input
            parent_id = request.POST.get('parent')  # from hidden input
            answer_url = request.POST.get('answer_url')  # from hidden input
            reply = form.save(commit=False)
            reply.answer = Answer(id=answer_id)
            reply.parent = Reply(id=parent_id)
            reply.user = request.user
            reply.save()
            return redirect(answer_url+'#'+str(reply.id))
    return redirect("/")


class AnswerPostView(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer_text','image']

    def get_context_data(self, **kwargs):
        kwargs['question'] = Question.objects.get(pk=self.kwargs.get('pk'))
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.question = Question.objects.get(pk=self.kwargs.get('pk'))
        messages.success(self.request, "Answer posted successfully!")
        return super().form_valid(form)


class AnswerDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Answer
    success_url = '/Query'

    def test_func(self):
        answer = self.get_object()

quesans/templates/quesans/answer_confirm_delete.html
{% extends "quesans/base_layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Answer</legend>
                <h2>Are you sure you want to delete your answer?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a href="{% url 'quesans:qthread' object.question.slug %} " class="btn btn-outline-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

quesans/templates/quesans/answer_form.html
{% extends 'quesans/base_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{form.media}}
  <div class="content-section">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Answer Question</legend>
        {{form|crispy}}
      </fieldset>
      <div class="form-group">
        <button type="btn btn-outline-info" type="submit">Post</button>
      </div>
    </form>
  </div>
{% endblock %}

quesans/templates/quesans/qlist.html
{% extends 'quesans/base_layout.html' %}
{% load mathfilters %}
{% block content %}
<div class="container mt-3">
  <div class="dropdown">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    Filter List
    </button>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'quesans:qlist' filter='answered' %}">Answered</a>
      <a class="dropdown-item" href="{% url 'quesans:qlist' filter='pending' %}">Pending</a>
      <a class="dropdown-item" href="{% url 'quesans:qlist' filter='bookmarked' %}">Bookmarked</a>
    </div>
  </div>
  {% for question in questions %}
  <article class="media content-section">
      <div class="ques-vote" style="display: flex; flex-direction: column;">
          <img class="rounded-circle article-img" src="{{question.author.profile.image.url }}" width='50' height='50' >
          <form action="{% url 'quesans:ques-voteup' %}" method="POST" style="display: inline-block;" class="upvote-form" id="{{ question.id }}">
              {% csrf_token %}
              <button type="submit" class="btn mt-1 upvote-btn{{ question.id }}" name="question_id" value="{{ question.id }}" style="background-color: transparent;">
              {% if question in uplst %}
              <i class="fas fa-caret-up upvoted" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:black"></i>
              {% else %}
              <i class="fas fa-caret-up upvote" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:grey"></i>
              {% endif %}
              </button>
          </form>
          <h5 class="vote-count{{question.id}}" style="margin-left: 18px;">{{question.qupvote.count|sub:question.qdownvote.count}}</h5>
          <form class="downvote-form" action="{% url 'quesans:ques-votedown' %}" method="POST" style="display: inline-block;" id="{{question.id}}">
              {% csrf_token %}
              <button type="submit" class="btn mt-1 downvote-btn{{question.id}}" name="question_id" value="{{ question.id }}" style="background-color: transparent;">
              {% if question in downlst %}
              <i class="fas fa-caret-down downvoted" style="font-size: 28px; margin-left: 5px;color:black"></i>
              {% else %}
              <i class="fas fa-caret-down downvote" style="font-size: 28px; margin-left: 5px;color:grey"></i>
              {% endif %}
              </button>
          </form>
      </div>
      <div class="media-body">
      <div class="article-metadata">
          <a class="mr-2" href="{% url 'profile-page' question.author.id %}">{{question.author}}</a>
          <small class="text-muted">{{question.created_on}}</small>
      </div>
      <p><a class="article-title" href="{% url 'quesans:qthread' question.slug %}">{{ question.title }}</a></p>
      <p class="question-description">{{ question.snippet|safe }}</p>
      </div>
      <form class="bookmark-form" action="{% url 'quesans:ques-bookmark' question.slug %}" method="POST" style="display: inline-block;" id="{{question.id}}">
          {% csrf_token %}
          <button type="submit" class="btn mt-1 bookmark-btn{{question.id}}" name="question_id" value="{{ question.id }}" style="background-color: transparent;">
          {% if question in bklst %}
          <i class="fas fa-bookmark bookmarked" style="font-size: 16px; margin-left: 5px;color:black"></i>
          {% else %}
          <i class="far fa-bookmark bookmark" style="font-size: 16px; margin-left: 5px;color:grey"></i>
          {% endif %}
          </button>
      </form>
      <a href="{% url 'quesans:qupdate' question.pk %}" class='btn' role='button' style="background-color: transparent;"><i class='fas fa-edit' style='font-size:16px;color:green'></i></a>
      {% if question.answered %}
      <span class="badge badge-danger">Closed</span>
      {% else %}
      <span class="badge badge-success">Open</span>
      {% endif %}
  </article>
  {% endfor %}
</div>
{% endblock %}
{% block script %}
<script>
       $(document).ready(function(){
            $(".nav-tabs a").click(function(){
                $(this).tab('show');
                console.log("tab changed")
                });
            $('.upvote-form').submit(function(e){
                e.preventDefault()
                //console.log('success')
                const question_id = $(this).attr('id')
                const url = $(this).attr('action')
                let res;
                const votes = $(`.vote-count${question_id}`).text()
                const trimCount = parseInt(votes)
                //console.log(trimCount)
                const upvoteText = $(`.upvote-btn${question_id}`).find("i").hasClass("upvoted") ? "Upvoted":"Upvote"
                const downvoteText = $(`.downvote-btn${question_id}`).find("i").hasClass("downvoted") ? "Downvoted":"Downvote"
                //console.log(upvoteText)
                trimup = $.trim(upvoteText)
                trimdown = $.trim(downvoteText)
                //console.log(trim)
                if(trimup == 'Upvoted') {
                   $(`.upvote-btn${question_id}`).html('<i class="fas fa-caret-up" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:grey"></i>')
                   res = trimCount - 1
                 } else if(trimdown == 'Downvoted'){
                   $(`.downvote-btn${question_id}`).html('<i class="fas fa-caret-down" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:grey"></i>')
                   $(`.upvote-btn${question_id}`).html('<i class="fas fa-caret-up" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:black"></i>')
                   res = trimCount + 2
                 }
                  else {
                    $(`.upvote-btn${question_id}`).html('<i class="fas fa-caret-up" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:black"></i>')
                    res = trimCount + 1
                }
                 $(`.vote-count${question_id}`).text(res)
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'question_id': question_id,
                    },
                    success: function(response) {
                       console.log('success')
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })
            })
          $('.downvote-form').submit(function(e){
            e.preventDefault()
            const question_id = $(this).attr('id')
            const url = $(this).attr('action')
            let res
            const votes = $(`.vote-count${question_id}`).text()
            const trimCount = parseInt(votes)
            //console.log(trimCount)
            const upvoteText = $(`.upvote-btn${question_id}`).find("i").hasClass("upvoted") ? "Upvoted":"Upvote"
            const downvoteText = $(`.downvote-btn${question_id}`).find("i").hasClass("downvoted") ? "Downvoted":"Downvote"
            //console.log(upvoteText)
            trimup = $.trim(upvoteText)
            trimdown = $.trim(downvoteText)
            //console.log(trim)
            if(trimdown == 'Downvoted') {
               $(`.downvote-btn${question_id}`).html('<i class="fas fa-caret-down" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:grey"></i>')
               res = trimCount + 1
             } else if(trimup == 'Upvoted'){
               $(`.upvote-btn${question_id}`).html('<i class="fas fa-caret-up" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:grey"></i>')
               $(`.downvote-btn${question_id}`).html('<i class="fas fa-caret-down" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:black"></i>')
               res = trimCount - 2
             }
             else {
                $(`.downvote-btn${question_id}`).html('<i class="fas fa-caret-down" style="font-size: 28px; margin-left: 5px; margin-top: 10px;color:black"></i>')
                res = trimCount - 1
            }
             $(`.vote-count${question_id}`).text(res)
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    'question_id': question_id,
                },
                success: function(response) {
                   console.log('success')
                },
                error: function(response) {
                    console.log('error', response)
                }
            })
          });
          $('.bookmark-form').submit(function(e){
            e.preventDefault()
            const question_id = $(this).attr('id')
            const url = $(this).attr('action')
            //console.log(trimCount)
            const bookmarkText = $(`.bookmark-btn${question_id}`).find("i").hasClass("bookmarked") ? "Bookmarked":"Bookmark"
            //console.log(upvoteText)
            trimtext = $.trim(bookmarkText)
            //console.log(trimtext)
            if(trimtext == 'Bookmarked') {
               $(`.bookmark-btn${question_id}`).html('<<i class="far fa-bookmark bookmark" style="font-size: 16px; margin-left: 5px;color:grey"></i>')

             }
             else {
                $(`.bookmark-btn${question_id}`).html('<i class="fas fa-bookmark bookmarked" style="font-size: 16px; margin-left: 5px;color:black"></i>')

            }

            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    'question_id': question_id,
                },
                success: function(response) {
                   console.log('success')
                },
                error: function(response) {
                    console.log('error', response)
                }
            })
          });
        });
</script>
{% endblock %}

quesans/templates/quesans/question_confirm_delete.html
{% extends "quesans/base_layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Question</legend>
                <h2>Are you sure you want to delete your question?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a href="{% url 'quesans:qthread' question.slug %} " class="btn btn-outline-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

quesans/templates/quesans/question_form.html
{% extends 'quesans/base_layout.html' %}
{% load crispy_forms_tags %}
{% block head %}{{form.media}}{% endblock %}
{% block content %}
  <div class="content-section">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Ask Question</legend>
        {{form|crispy}}
      </fieldset>
      <div class="form-group">
        <button type="btn btn-outline-info" type="submit">Post</button>
      </div>
    </form>
  </div>
{% endblock %}

quesans/templates/quesans/reply.html
<div class="reply border-0 border-start border-2 ps-2" id="{{reply.id}}">
  <a href="#{{reply.id}}" class="reply-border-link">
      <span class="sr-only">Jump to reply {{reply.id}}</span>
  </a>
        <div class="mt-3">
            <strong>{{reply.user.username}}</strong>
            {% if  reply.parent.user.username%} to <strong>{{reply.parent.user.username}}</strong>{% endif %}
            <small class="text-muted">On {{ reply.created.date }}</small>
        </div>
        <div class="border p-2 rounded">
            <p>{{reply.body}}</p>
            <button class="btn btn-primary btn-sm" onclick="handleReply({{reply.id}})">Reply</button>

            <div id="reply-form-container-{{reply.id}}" style="display:none">

                <form method="post" action="{% url 'quesans:reply' %}" class="mt-3">
                    {% csrf_token %}
                    <input type="hidden" name="answer_id" value="{{answer.id}}">
                    <input type="hidden" name="parent" value="{{reply.id}}">
                    <input type="hidden" name="answer_url" value="{% url 'quesans:ans-detail' answer.pk %}">
                    {{reply_form.as_p}}
                    <div>
                        <button type="button" onclick="handleCancel({{reply.id}})" class="btn btn-light border btn-sm">Cancel</button>
                        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        {% for reply in reply.get_replies %}
            {% include 'quesans/reply.html' with reply=reply %}
        {% endfor %}
</div>

quesans/templates/quesans/search-ques.html
{% extends 'quesans/base_layout.html' %}
{% block content %}
<h4 class="display-4">Can't find a question? Search for it here</h4>
<br>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'quesans:qsearch' %}" >
            <input class="form-control mr-sm-2" type="search" name="search" placeholder="Enter title">
            <button class="btn btn btn-outline-info my-2 my-sm-0" type="submit"> Search </button>
    </form>
<br>
<h3 class="display-4">Your Results -</h3>
{% for question in search_results %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{question.author.profile.image.url }}" width='50' height='50' >
    <div class="media-body">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'profile-page' question.author.id %}">{{question.author}}</a>
        <small class="text-muted">{{question.created_on}}</small>
    </div>
    <h2><a class="article-title" href="{% url 'quesans:qthread' question.slug %}">{{ question.title }}</a></h2>
    <p class="article-content">{{ question.snippet }}</p>
    </div>
    {% if question.answered %}
    <span class="badge badge-danger">Closed</span>
    {% else %}
    <span class="badge badge-success">Open</span>
    {% endif %}
</article>
<br>
{% empty %}
<div class="container-fluid my-3 pt-4">
  <h3 class="display-3">No Results found!</h3>
</div>
{% endfor %}
{% endblock %}